/* AEON OPS — Logo Patch v1.0 — auto-generated, 77 logos */
(function(){
  const LOGOS = {
  "ai_genspark": "logos/ai_genspark.png",
  "dv_replicate": "logos/dv_replicate.png",
  "vd_leonardo": "logos/vd_leonardo.png",
  "dv_v0": "logos/dv_v0.png",
  "ad_mercury": "logos/ad_mercury.png",
  "dv_emergent": "logos/dv_emergent.png",
  "dv_railway2": "logos/dv_railway2.png",
  "ai_roocode": "logos/ai_roocode.png",
  "ai_elevenlabs": "logos/ai_elevenlabs.png",
  "ai_perplexity": "logos/ai_perplexity.png",
  "dv_digitalocean": "logos/dv_digitalocean.png",
  "vd_runway": "logos/vd_runway.png",
  "dv_hetzner": "logos/dv_hetzner.png",
  "vd_synthesia": "logos/vd_synthesia.png",
  "ad_telegram": "logos/ad_telegram.png",
  "ad_azure": "logos/ad_azure.png",
  "ai_xai": "logos/ai_xai.png",
  "vd_hailuo": "logos/vd_hailuo.png",
  "dv_gitlab": "logos/dv_gitlab.png",
  "ai_lovable": "logos/ai_lovable.png",
  "vd_kling": "logos/vd_kling.png",
  "ai_kimi": "logos/ai_kimi.png",
  "dv_vercel": "logos/dv_vercel.png",
  "ai_zhipu": "logos/ai_zhipu.png",
  "dv_windsurf": "logos/dv_windsurf.png",
  "ad_gcloud": "logos/ad_gcloud.png",
  "ai_copilot": "logos/ai_copilot.png",
  "ad_neo": "logos/ad_neo.png",
  "ai_chatgpt": "logos/ai_chatgpt.png",
  "ai_openai": "logos/ai_openai.png",
  "vd_invideo": "logos/vd_invideo.png",
  "ai_anthropic": "logos/ai_anthropic.png",
  "ai_gemini": "logos/ai_gemini.png",
  "ai_codex": "logos/ai_codex.png",
  "ad_gdrive": "logos/ad_gdrive.png",
  "dv_posthog": "logos/dv_posthog.png",
  "dv_github": "logos/dv_github.png",
  "dv_zitadel": "logos/dv_zitadel.png",
  "ai_zencoder": "logos/ai_zencoder.png",
  "ai_minimax": "logos/ai_minimax.png",
  "ai_deepseek": "logos/ai_deepseek.png",
  "vd_ltx": "logos/vd_ltx.png",
  "ai_meta": "logos/ai_meta.png",
  "dv_notion": "logos/dv_notion.png",
  "ai_polsia": "logos/ai_polsia.png",
  "dv_lightning": "logos/dv_lightning.png",
  "ad_gmail": "logos/ad_gmail.png",
  "ai_creatify": "logos/ai_creatify.png",
  "ai_fastgpt": "logos/ai_fastgpt.png",
  "ai_huggingface": "logos/ai_huggingface.png",
  "dv_railway": "logos/dv_railway.png",
  "ad_dropbox": "logos/ad_dropbox.png",
  "ai_claude": "logos/ai_claude.png",
  "ad_spotify": "logos/ad_spotify.png",
  "dv_supabase": "logos/dv_supabase.png",
  "ai_lambda": "logos/ai_lambda.png",
  "dv_n8n": "logos/dv_n8n.png",
  "ai_livekit": "logos/ai_livekit.png",
  "dv_airtable": "logos/dv_airtable.png",
  "dv_augment": "logos/dv_augment.png",
  "dv_cursor": "logos/dv_cursor.png",
  "dv_vast": "logos/dv_vast.png",
  "dv_hivelocity": "logos/dv_hivelocity.png",
  "ai_grok": "logos/ai_grok.png",
  "ad_ghl": "logos/ad_ghl.png",
  "ad_canva": "logos/ad_canva.png",
  "dv_zapier": "logos/dv_zapier.png",
  "ai_capcut": "logos/ai_capcut.png",
  "ai_mistral": "logos/ai_mistral.png",
  "dv_stripe": "logos/dv_stripe.png",
  "dv_lovable": "logos/dv_lovable.png",
  "vd_visla": "logos/vd_visla.png",
  "dv_cloudflare": "logos/dv_cloudflare.png",
  "dv_clerk": "logos/dv_clerk.png",
  "ai_requesty": "logos/ai_requesty.png",
  "dv_sentry": "logos/dv_sentry.png",
  "ai_collaby": "logos/ai_collaby.png"
};
  const ID_MAP = {
  "ai1": "ai_claude",
  "ai2": "ai_chatgpt",
  "ai3": "ai_codex",
  "ai4": "ai_grok",
  "ai5": "ai_gemini",
  "ai6": "ai_perplexity",
  "ai7": "ai_mistral",
  "ai8": "ai_deepseek",
  "ai9": "ai_meta",
  "ai10": "ai_copilot",
  "ai11": "ai_kimi",
  "ai12": "ai_genspark",
  "ai13": "ai_minimax",
  "ai14": "ai_elevenlabs",
  "ai16": "ai_capcut",
  "ai17": "ai_requesty",
  "ai19": "ai_polsia",
  "ai20": "ai_xai",
  "ai21": "ai_livekit",
  "ai22": "ai_fastgpt",
  "ai25": "ai_zhipu",
  "ai27": "ai_huggingface",
  "ai28": "ai_creatify",
  "ai31": "ai_zencoder",
  "ai33": "ai_roocode",
  "ai34": "ai_lambda",
  "ai35": "ai_collaby",
  "ai36": "ai_livekit",
  "ai37": "ai_anthropic",
  "ai38": "ai_openai",
  "ai39": "ai_gemini",
  "ai40": "ai_lovable",
  "dv1": "dv_github",
  "dv2": "dv_github",
  "dv3": "dv_gitlab",
  "dv4": "dv_vercel",
  "dv5": "dv_v0",
  "dv6": "dv_supabase",
  "dv7": "dv_supabase",
  "dv8": "dv_airtable",
  "dv9": "dv_stripe",
  "dv10": "dv_n8n",
  "dv11": "dv_zitadel",
  "dv12": "dv_cloudflare",
  "dv13": "dv_cloudflare",
  "dv14": "dv_clerk",
  "dv15": "dv_railway",
  "dv16": "dv_digitalocean",
  "dv17": "dv_hivelocity",
  "dv18": "dv_hetzner",
  "dv19": "dv_vast",
  "dv20": "dv_lightning",
  "dv21": "dv_replicate",
  "dv22": "dv_windsurf",
  "dv23": "dv_cursor",
  "dv24": "dv_augment",
  "dv25": "dv_sentry",
  "dv26": "dv_posthog",
  "dv27": "dv_zapier",
  "dv34": "dv_notion",
  "ad1": "ad_gmail",
  "ad2": "ad_neo",
  "ad3": "ad_mercury",
  "ad6": "ad_gcloud",
  "ad7": "ad_gdrive",
  "ad14": "ad_ghl",
  "ad15": "ad_spotify",
  "ad16": "ad_telegram",
  "ad17": "ad_canva",
  "ad12": "ad_azure",
  "vd1": "vd_hailuo",
  "vd3": "vd_leonardo",
  "vd4": "vd_kling",
  "vd5": "vd_runway",
  "vd6": "vd_invideo",
  "vd9": "vd_synthesia",
  "vd10": "vd_ltx",
  "vd11": "vd_visla",
  "vd12": "vd_luma",
  "vd14": "vd_midjourney",
  "tl2": "tl_telnyx",
  "tl3": "tl_telnyx",
  "tl4": "tl_twilio",
  "ui1": "ui_shadcn",
  "ui2": "ui_mui",
  "ui10": "ui_magic",
  "ui11": "ui_aceternity",
  "gg1": "gg_sheets",
  "gg4": "gg_calendar",
  "gg7": "gg_analytics",
  "gg11": "gg_apollo",
  "gg12": "gg_hunter",
  "gg6": "gg_notebooklm"
};

  function swapIcons() {
    document.querySelectorAll('.card').forEach(function(card) {
      const cid = card.dataset.cardId;
      const lid = ID_MAP[cid];
      if (!lid || !LOGOS[lid]) return;
      const icon = card.querySelector('.card-icon');
      if (!icon || icon.dataset.swapped) return;
      const fallback = icon.textContent;
      const img = document.createElement('img');
      img.src = LOGOS[lid];
      img.style.cssText = 'width:22px;height:22px;object-fit:contain;border-radius:3px;display:block;';
      img.loading = 'lazy';
      img.alt = '';
      img.onerror = function() { icon.textContent = fallback; };
      icon.textContent = '';
      icon.appendChild(img);
      icon.dataset.swapped = '1';
    });
  }

  // Watch for re-renders (tabs, drag-drop)
  const obs = new MutationObserver(function() { setTimeout(swapIcons, 50); });
  obs.observe(document.body, {childList: true, subtree: true});
  document.addEventListener('DOMContentLoaded', swapIcons);
  setTimeout(swapIcons, 300);
})();
